# Generated by Django 2.0.7 on 2018-08-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxeldesigner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='current_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
