# Generated by Django 2.0.7 on 2018-08-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyxeldesigner', '0004_problem_elezo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='latest_submission',
            new_name='final_submission',
        ),
    ]
