# Generated by Django 2.0.7 on 2018-08-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyxeldesigner', '0005_auto_20180809_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bonus_first_solves_in_stream',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='total_first_solves_in_stream',
            field=models.IntegerField(default=0),
        ),
    ]
