# Generated by Django 2.0.7 on 2018-07-11 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('stream', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('initial_code', models.TextField()),
                ('goal_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_submission', models.TextField(blank=True)),
                ('passed', models.BooleanField(default=False)),
                ('started_dtstamp', models.DateTimeField(auto_now_add=True)),
                ('passed_dtstamp', models.DateTimeField(blank=True, null=True)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hifadhidata.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('form', models.IntegerField()),
                ('stream', models.CharField(choices=[('A', 'A Stream'), ('B', 'B Stream')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bonus_pass_percent', models.IntegerField(default=0)),
                ('bonus_first_solves_in_stream', models.IntegerField(default=0)),
                ('total_pass_percent', models.IntegerField(default=0)),
                ('total_first_solves_in_stream', models.IntegerField(default=0)),
                ('motivation_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hifadhidata.Student'),
        ),
    ]
