# Generated by Django 2.0.7 on 2018-07-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifadhidata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='goal_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='initial_code',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer_sql',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
