# Generated by Django 2.0.7 on 2018-07-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifadhidata', '0002_auto_20180711_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='elezo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
