# Generated by Django 2.0.7 on 2018-07-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifadhidata', '0003_problem_elezo'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='required_tables',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
