# Generated by Django 2.0.7 on 2018-07-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifadhidata', '0004_problem_required_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='table_font_size',
            field=models.TextField(default='1em'),
            preserve_default=False,
        ),
    ]
