# Generated by Django 2.0.7 on 2018-08-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifadhidata', '0005_problem_table_font_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_partitioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problem',
            name='partitioned_create_ddl',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='partitioned_load_stmts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
