# Generated by Django 2.0.7 on 2018-08-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifadhidata', '0006_auto_20180816_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_insert_update_delete_only',
            field=models.BooleanField(default=False),
        ),
    ]
