# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengamtandao', '0002_client_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('form', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
