# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jengamtandao', '0016_auto_20171023_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='html_desc',
            new_name='goal_code',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='verify_code',
        ),
    ]
