# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jengamtandao', '0017_auto_20180224_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='num_submissions',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_submissions',
        ),
    ]
