# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengamtandao', '0018_auto_20180224_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='passed_tests_percent',
        ),
        migrations.AddField(
            model_name='progress',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
