# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengamtandao', '0019_auto_20180224_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='motivation_index',
            field=models.IntegerField(default=0),
        ),
    ]
