# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('html_desc', models.TextField()),
                ('initial_code', models.TextField()),
                ('verify_code', models.TextField()),
            ],
        ),
    ]
