# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-07 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20171023_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
