# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-07 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_problem_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='motivation_index',
            field=models.IntegerField(default=0),
        ),
    ]
