17	Order Planets By Rings, Then By Name	2	SELECT * FROM sayari ORDER BY has_rings, name;	Order all of the planets by whether they have rings: planets <b>without</b> rings should come first. Then order alphabetically by name (A to Z). You should select all columns.
8	Planets with Rings and Gravity Less than 10	1	SELECT name, gravity FROM sayari WHERE has_rings = True AND gravity < 10;	Select the name and gravity columns for all planets with rings and with gravity less than 10 m/s<sup>2</sup>.
7	Planets with Gravity Not Equal to 3.7	1	SELECT * FROM sayari WHERE gravity != 3.7;	Mars and Mercury have the same gravity: 3.7 m/s<sup>2</sup>. Select all columns for all planets whose gravity <b>is not</b> 3.7 m/s<sup>2</sup>.
6	Planets That Are Not Named "Earth"	1	SELECT * FROM sayari WHERE NOT name = 'Earth';	Select all columns for all planets that are not named "Earth."
5	Planets with Gravity Greater than 10	1	SELECT name, gravity FROM sayari WHERE gravity > 10;	Find all planets that have gravities greater than 10 m/s<sup>2</sup>. <b>Only select the name and gravity columns.</b>
4	Planets with Gravity Less than 9	1	SELECT name, gravity FROM sayari WHERE gravity < 9;	Find all planets that have gravities less than 9 m/s<sup>2</sup>. <b>Only select the name and gravity columns.</b>
3	Planets with Rings	1	SELECT name FROM sayari WHERE has_rings = True;	Find all the planets that have rings around them. <b>Only select their names. No other columns should be visible.</b>
2	All Planets (Name and Gravity Only)	1	SELECT name, gravity FROM sayari;	Select <b>only</b> the name and gravity values for all planets. No other columns should be visible.
1	All Planets	1	SELECT * FROM sayari;	Select every planet. Your query should return all columns.
9	Planets Named "Venus" or "Neptune"	1	SELECT * FROM sayari WHERE name = 'Neptune' OR name = 'Venus';	Select all columns for all planets that are either named "Venus" or "Neptune."
10	Planets Named  "Mars," "Saturn," or "Pluto"	1	SELECT * FROM sayari WHERE name = 'Mars' OR name = 'Saturn' OR name = 'Pluto';	Select all columns for those planets named either "Mars," "Saturn," or "Pluto."
11	Planets with Gravity Between 1 and 5	1	SELECT name, gravity FROM sayari WHERE gravity > 1 AND gravity < 5;	Select the name and gravity columns for all planets with gravity between 1 and 5 m/s<sup>2</sup>.
12	Planets with Gravity Between 6 and 10	1	SELECT name, gravity FROM sayari WHERE gravity > 6 AND gravity < 10;	Select the name and gravity columns for all planets with a gravity between 6 and 10 m/s<sup>2</sup>.
13	Order Planets By Rings, Then By Gravity	2	SELECT * FROM sayari ORDER BY has_rings, gravity;	Order all of the planets by whether they have rings: planets <b>without</b> rings should come first. Then order by increasing gravity. You should select all columns.
14	Order All Planets Alphabetically (A to Z)	2	SELECT * FROM sayari ORDER BY name ASC;	Select all columns for all of the planets, and order them alphabetically from A to Z.
15	Order All Planets Alphabetically (Z to A)	2	SELECT * FROM sayari ORDER BY name DESC;	Select all columns for all the planets, and order them by name in <b>reverse alphabetical order</b> (from Z to A).
16	Planets with Gravity < 9.5, Ordered By Decreasing Gravity	2	SELECT name, gravity FROM sayari WHERE gravity < 9.5 ORDER BY gravity DESC;	Select the name and gravity columns for all planets with gravity less than 9.5. Order them from largest to smallest (decreasing) gravity.
