# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0005_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_seqnum', models.IntegerField()),
                ('latest_submission', models.TextField()),
                ('num_submissions', models.IntegerField(default=0)),
                ('passed_tests_percent', models.IntegerField(default=0)),
                ('started_dtstamp', models.DateTimeField(auto_now_add=True)),
                ('passed_dtstamp', models.DateTimeField()),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyokatofali.Problem')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nyokatofali.Student')),
            ],
        ),
    ]
