# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0009_auto_20170926_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='problem_seqnum',
        ),
    ]
