# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0010_remove_progress_problem_seqnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_pass_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_submissions',
            field=models.IntegerField(default=0),
        ),
    ]
