# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0014_auto_20171002_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField()),
                ('stream', models.CharField(max_length=1)),
            ],
        ),
    ]
