# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0015_accesswhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bonus_first_solves_in_stream',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='bonus_pass_percent',
            field=models.IntegerField(default=0),
        ),
    ]
