# Generated by Django 2.0.7 on 2018-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0018_student_motivation_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='preamble_code',
            field=models.TextField(blank=True),
        ),
    ]
