# Generated by Django 2.0.7 on 2018-07-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyokatofali', '0020_remove_problem_preamble_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='enabled',
        ),
    ]
