18	Names of Girls Taking NECTA Exam in 2017	3	SELECT name FROM tsss_necta_results_2017 WHERE sex = 'F';	Find <b>only the names</b> of girls who took the NECTA exam at TSSS last year.	tsss_necta_results_2017	0.8em
23	Boys Who Scored Between 2 and 11 Points	3	SELECT cno, name, points FROM tsss_necta_results_2017\r\nWHERE sex = 'M' AND points BETWEEN 2 and 11;	Display the candidate number, name, and points for those boys who scored between 2 and 11 points.	tsss_necta_results_2017	0.8em
24	NECTA Division 1 Boys	3	SELECT cno, name FROM tsss_necta_results_2017 WHERE sex = 'M' and division = 1;	Find the candidate numbers and names of all boys in Division 1.	tsss_necta_results_2017	0.8em
19	"A" Students in 2017 NECTA Math	3	SELECT cno, name FROM tsss_necta_results_2017 WHERE math = 'A';	Display the candidate number and name of those students who scored an A in math.	tsss_necta_results_2017	0.8em
20	"B" Students in 2017 NECTA Civics	3	SELECT cno, name FROM tsss_necta_results_2017 WHERE civ = 'B';	Display the candidate number and name of those students who scored a B in civics.	tsss_necta_results_2017	0.8em
21	"C" Students in 2017 NECTA ICT	3	SELECT cno, name FROM tsss_necta_results_2017 WHERE ict = 'C';	Display the candidate number and name of those students who scored a C in ICT.	tsss_necta_results_2017	0.8em
22	Girls Who Scored Between 1 and 10 Points	3	SELECT cno, name, points FROM tsss_necta_results_2017\r\nWHERE sex = 'F'\r\nAND points >= 1\r\nAND points <= 10;	Display the candidate number, name, and points for those girls who scored between 1 and 10 points.	tsss_necta_results_2017	0.8em
25	NECTA Division 1 Girls	3	SELECT cno, name FROM tsss_necta_results_2017 WHERE sex = 'F' and division = 1;	Find the candidate numbers and names of all girls in Division 1.	tsss_necta_results_2017	0.8em
26	Students Scoring "A" in Both Swahili and English	3	SELECT name FROM tsss_necta_results_2017\r\nWHERE kiswahili = 'A'\r\nAND english = 'A';	Find the names of all students who scored an "A" in <b>both</b> Kiswahili and English.	tsss_necta_results_2017	0.8em
27	Boys Scoring "A" in Either Biology or Chemistry	3	SELECT * FROM tsss_necta_results_2017\r\nWHERE sex = 'M'\r\nAND (bio = 'A' OR chem = 'A');	Select <b>all columns</b> for boys who scored an "A" in <b>either</b> biology <b>or</b> chemistry.	tsss_necta_results_2017	0.8em
28	Girls Scoring "A" in Either Physics or Math	3	SELECT * FROM tsss_necta_results_2017\r\nWHERE sex = 'F'\r\nAND (physics = 'A' OR math = 'A');	Select <b>all columns</b> for girls who scored an "A" in <b>either</b> physics <b>or</b> math.	tsss_necta_results_2017	0.8em
29	NECTA Candidate Number 30	3	SELECT name, sex FROM tsss_necta_results_2017 WHERE cno = 30;	Find the name and sex of the student who is candidate number 30.	tsss_necta_results_2017	0.8em
30	NECTA Candidate Number 6	3	SELECT name, sex FROM tsss_necta_results_2017 WHERE cno = 6;	Find the name and sex of the student who is candidate number 6.	tsss_necta_results_2017	0.8em
31	Order all NECTA Students by Decreasing Candidate Number	4	SELECT cno, name\r\nFROM tsss_necta_results_2017\r\nORDER BY cno DESC;	Display the candidate number and name for all students. Order them by decreasing candidate number.	tsss_necta_results_2017	0.8em
32	Order all Girls by Their NECTA Division	4	SELECT name, division FROM tsss_necta_results_2017\r\nWHERE sex = 'F'\r\nORDER BY division;	Display the name and division of all girls who took the NECTA exam. Order them from lowest to to highest division.	tsss_necta_results_2017	0.8em
33	Order all Boys by Their NECTA Division	4	SELECT name, division FROM tsss_necta_results_2017\r\nWHERE sex = 'M'\r\nORDER BY division;	Display the name and division of all boys who took the NECTA exam. Order them from lowest to to highest division.	tsss_necta_results_2017	0.8em
34	Same NECTA Grades in Geo, Hist, and Swahili	4	SELECT * FROM tsss_necta_results_2017\r\nWHERE geo = hist AND hist = kiswahili;	Display all columns for those students whose scores in geography, history, and Kiswahili <b>are all the same</b>.	tsss_necta_results_2017	0.8em
35	Same NECTA Grades in English, Physics, Chem, and Bio	4	SELECT * FROM tsss_necta_results_2017\r\nWHERE english = physics\r\nAND physics = chem\r\nAND chem = bio;	Display all columns for those students whose scores in English, physics, chemistry, and biology <b>are all the same</b>.	tsss_necta_results_2017	0.8em
36	Students who Did Not Score an "A" in Biology	3	SELECT name, bio\r\nFROM tsss_necta_results_2017\r\nWHERE bio != 'A';	Display the names and biology grades of those students who did not score an A in biology.	tsss_necta_results_2017	0.8em
37	Girls who Did Not Score an "A" in Physics	3	SELECT name, physics\r\nFROM tsss_necta_results_2017\r\nWHERE physics != 'A' AND sex = 'F';	Display the names and physics grades of those girls who did not score an A in physics.	tsss_necta_results_2017	0.8em
38	Boys who Did Not Score an "A" in Chemistry	3	SELECT name, chem\r\nFROM tsss_necta_results_2017\r\nWHERE chem != 'A' AND sex = 'M';	Display the names and chemistry grades of those boys who did not score an A in chemistry.	tsss_necta_results_2017	0.8em
39	Order Girls by NECTA Civics, History Grades	4	SELECT name, civ, hist FROM tsss_necta_results_2017\r\nWHERE sex = 'F'\r\nORDER BY civ, hist;	Display the names, civics grade, and history grade for all girls. Order them first by their civics grade, then by their history grade.	tsss_necta_results_2017	0.8em
40	Order Boys by NECTA English, Kiswahili Grades	4	SELECT name, english, kiswahili FROM tsss_necta_results_2017\r\nWHERE sex = 'M'\r\nORDER BY english, kiswahili;	Display the names, English grade, and Kiswahili grade for all boys. Order them first by their English grade, then by their Kiswahili grade.	tsss_necta_results_2017	0.8em
