49	Number of Transactions Sent from Karatu	5	SELECT COUNT(*) FROM bank_txns_2018\r\nWHERE location = 'Karatu';	Count the number of transactions that were sent from Karatu.	bank_txns_2018	1em
50	Number of Transactions Sent from Makuyuni	5	SELECT COUNT(*) FROM bank_txns_2018\r\nWHERE location = 'Makuyuni';	Count the number of transactions that were sent from Makuyuni.	bank_txns_2018	1em
41	Number of Processing Bank Transactions	5	SELECT COUNT(*) FROM bank_txns_2018 WHERE status = 'PROCESSING';	Find the number of bank transactions that are still processing.	bank_txns_2018	1em
42	Number of Completed Bank Transactions	5	SELECT COUNT(*) FROM bank_txns_2018 WHERE status = 'COMPLETED';	Find the number of bank transactions that have been completed.	bank_txns_2018	1em
51	Number of Transactions Sent from Arusha or Mto wa Mbu	5	SELECT COUNT(*) FROM bank_txns_2018\r\nWHERE location = 'Arusha' or location = 'Mto wa Mbu';	Count the number of transactions that were sent from Arusha or Mto wa Mbu.	bank_txns_2018	1em
52	Lowest Amount Sent by James via ATM	5	SELECT MIN(shillings) FROM bank_txns_2018\r\nWHERE sender = 'James' AND method = 'ATM';	Find the lowest amount of money sent by James using an ATM.	bank_txns_2018	1em
43	Transactions from Anitha to Hosiana	5	SELECT * FROM bank_txns_2018\r\nWHERE sender = 'Anitha' and recipient = 'Hosiana';	Find the transaction in which Anitha sent Hosiana money. Display all columns of that transaction.	bank_txns_2018	1em
44	All Transactions Sent By Christiner	5	SELECT * FROM bank_txns_2018\r\nWHERE sender = 'Christiner';	Find all the transactions in which Christiner sent money to someone. You should display all columns of those transactions.	bank_txns_2018	1em
45	Transactions Where Fred Recvd 50k Or More	5	SELECT COUNT(*) FROM bank_txns_2018\r\nWHERE recipient = 'Fred' and shillings > 50000;	Count the number of transactions where Fred received 50,000 shillings or more.	bank_txns_2018	1em
46	Jackson's and Uta's Txns Ordered By Datetime	5	SELECT * FROM bank_txns_2018\r\nWHERE sender = 'Jackson' OR sender = 'Uta'\r\nORDER BY datetime_sent;	Display all columns for all transactions sent by Uta or Jackson. Order the transactions by the datetime they were sent (oldest to newest).	bank_txns_2018	1em
47	The Most Amount of Money Irene Sent	5	SELECT MAX(shillings) FROM bank_txns_2018\r\nWHERE sender = 'Irene';	Find the highest amount of shillings sent by Irene to another person.	bank_txns_2018	1em
48	Recipient of Faraja's MPESA Transaction	5	SELECT recipient FROM bank_txns_2018\r\nWHERE sender = 'Faraja' and method = 'MPESA';	Faraja sent money to someone using MPESA in only one transaction. Find <b>only the recipient</b> of that transaction.	bank_txns_2018	1em
53	Order Loveness' Transactions By Decreasing ID	5	SELECT * FROM bank_txns_2018\r\nWHERE sender = 'Loveness'\r\nORDER BY txnid DESC;	Display all columns of all transactions sent by Loveness. Order them from highest to lowest transaction ID.	bank_txns_2018	1em
54	Earilest Time Frank Sent Between 10k and 90k TSH	6	SELECT MIN(datetime_sent) FROM bank_txns_2018\r\nWHERE sender = 'Frank' AND shillings BETWEEN 10000 AND 90000;	Find the earliest datetime when Frank sent between 10,000 and 90,000 shillings to someone.	bank_txns_2018	1em
55	Most Recent Time Upendo Sent Between 50k and 110k TSH	6	SELECT MAX(datetime_sent) FROM bank_txns_2018\r\nWHERE sender = 'Upendo' AND shillings BETWEEN 50000 AND 110000;	Find the most recent datetime when Upendo sent between 50,000 and 110,000 shillings to someone.	bank_txns_2018	1em
56	Dorcus' Transactions from Karatu Office	6	SELECT txnid FROM bank_txns_2018\r\nWHERE sender = 'Dorcus' and method = 'Bank Office' and location = 'Karatu';	Display <b>only the txnids</b> of those transactions where Dorcus sent money from the bank office in Karatu.	bank_txns_2018	1em
57	Endesh and Sandra's Txns From ATM	6	SELECT * FROM bank_txns_2018\r\nWHERE method = 'ATM' AND (sender = 'Endesh' OR sender = 'Sandra');	Display all columns of those transactions where <b>either</b> Endesh <b>or</b> Sandra sent money using an ATM.	bank_txns_2018	1em
58	Chris/Loishiye Txns Sent to Salum/Edwin/Japhet	6	SELECT * FROM bank_txns_2018\r\nWHERE (sender = 'Christopher' OR sender = 'Loishiye')\r\nAND (recipient = 'Salum' OR recipient = 'Japhet' OR recipient = 'Edwin');	Display all columns of those transactions where <b>either</b> Christopher <b>or</b> Loishiye sent money to <b>either</b> Salum, Edwin, <b>or</b> Japhet.	bank_txns_2018	1em
59	Shillings Received by Godlisten or Jackline	6	SELECT shillings FROM bank_txns_2018\r\nWHERE recipient = 'Godlisten' OR recipient = 'Jackline'\r\nORDER BY shillings DESC;	Display <b>only the shillings</b> received by <b>either</b> Godlisten <b>or</b> Jackline. Order the amount of shillings from highest to lowest.	bank_txns_2018	1em
60	Lowest and Highest Amounts Sent by Eliana	6	SELECT MIN(shillings), MAX(shillings) FROM bank_txns_2018\r\nWHERE sender = 'Eliana';	Display <b>both</b> the lowest <b>and</b> highest amounts of shillings sent by Eliana.	bank_txns_2018	1em
61	Lowest and Highest Amounts Sent via MPESA	6	SELECT MIN(shillings), MAX(shillings) FROM bank_txns_2018\r\nWHERE method = 'MPESA';	Display <b>both</b> the lowest <b>and</b> highest amounts of shillings sent using MPESA.	bank_txns_2018	1em
62	Count the Number of Txns Sent Outside of Manyara	6	SELECT COUNT(*) FROM bank_txns_2018\r\nWHERE location != 'Manyara';	Count the number of transactions that <b>were not</b> sent from Manyara.	bank_txns_2018	1em
63	Earliest and Latest Datetimes Maria Sent Money	6	SELECT MIN(datetime_sent), MAX(datetime_sent) FROM bank_txns_2018\r\nWHERE sender = 'Maria';	Display <b>both</b> the earliest <b>and</b> most recent datetimes when Maria sent money.	bank_txns_2018	1em
64	Completed Transactions for Josephat and Neema	6	SELECT COUNT(*) FROM bank_txns_2018\r\nWHERE (sender = 'Josephat' OR sender = 'Neema')\r\nAND status = 'COMPLETED';	Count the number of <b>completed</b> transactions sent <b>either</b> by Josephat <b>or</b> Neema.	bank_txns_2018	1em
