149	People in the Minerals Industry	57	SELECT wafanyabiashara.name\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE industry_type = 'Minerals';	Select <b>only the names</b> of people working in the minerals industry.	business, wafanyabiashara	1em	f		
148	Display All Businesspeople + Their Businesses	56	SELECT wafanyabiashara.name, business.name\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id;	Display the name of all businesspeople along with the name of the business they are running.	business, wafanyabiashara	1em	f		
153	Names of all Businesspeople in Dodoma	58	SELECT wafanyabiashara.name\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE city = 'Dodoma';	Display the names of all people doing business in Dodoma.	business, wafanyabiashara	1em	f		
147	People in the Fashion Industry	57	SELECT wafanyabiashara.name\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE industry_type = 'Fashion';	Select <b>only the names</b> of people working in the fashion industry.	business, wafanyabiashara	1em	f		
151	Aerospace Industry Businesspeople	58	SELECT business.name, wafanyabiashara.name, sex\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE industry_type = 'Aerospace';	Display the business name, businessperson name, and businessperson's gender for companies in the aerospace industry.	business, wafanyabiashara	1em	f		
150	Names and Address of Dar Businesspeople	58	SELECT wafanyabiashara.name, business.address\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE city = 'Dar es Salaam';	Display the name and address of businesspeople working in Dar.	business, wafanyabiashara	1em	f		
154	Names + Industries of People in Private Industry	59	SELECT wafanyabiashara.name, industry_type\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE is_private = True;	Display the names and industries of people doing business privately.	business, wafanyabiashara	1em	f		
152	Names of all Dodoma Businesses	58	SELECT name\r\nFROM business\r\nWHERE city = 'Dodoma';	Display the names of all Dodoma businesses.	business, wafanyabiashara	1em	f		
155	Businesspeople at Companies of Value TSH 500M Or More	59	SELECT wafanyabiashara.name, business.name, total_value\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE total_value >= 500000000;	Display the businessperson's name, their business name, and their business' value for people working at businesses valued at 500 million shillings or more.	business, wafanyabiashara	1em	f		
156	Count Women in Dodoma Businesses	60	SELECT COUNT(*)\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE sex = 'F' AND city = 'Dodoma';	Count the number of women working in Dodoma businesses.	business, wafanyabiashara	1em	f		
157	Earliest Start Date of People in Consulting Industry	60	SELECT MIN(start_date)\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE industry_type = 'Consulting';	Find the earliest start date among businesspeople working in the consulting industry.	business, wafanyabiashara	1em	f		
158	Value of Businesses in all Industries	60	SELECT SUM(total_value)\r\nFROM business;	Find the <b>total</b> value of businesses in <b>all industries.</b>	business, wafanyabiashara	1em	f		
159	Number of Males Working at Government Companies	61	SELECT COUNT(*)\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE is_private = False AND sex = 'M';	Find the number of males working at government (non-private) companies.	business, wafanyabiashara	1em	f		
160	Nchiyetu Aerospace Order by Start Date	61	SELECT wafanyabiashara.name, start_date\r\nFROM wafanyabiashara\r\nJOIN business\r\nON wafanyabiashara.business_id = business.id\r\nWHERE business.name = 'Nchiyetu Aerospace, Inc.'\r\nORDER BY start_date DESC;	Display the names and start dates of businesspeople working at Nchiyetu Aerospace. Order them by their start date (most recent to earliest).	business, wafanyabiashara	1em	f		
